### ISSUE TITLE
Doesn't just append, replaces if any other plugin also uses it.

### ISSUE THREAD

**Issue by RationalSquash** [gnargle/NICEDamage#2]
Noticed subtext from other plugins stopped showing up after this was turned on. When disabled, they worked again. 
An example would be the text showing the user when having the "pat me" plugin enabled.
Seems like its overwriting/blanking out text from everything else when it checks if it ends with 69.
While the plugin is expected to be harmless, this can cause issues so i'll be removing it for now. 

To be fixed, i assume this part would need to somehow append instead of overwriting the value.
https://github.com/gnargle/NICEDamage/blob/377df5a89e00bedb090e8b61da625e85af25c775/NICEDamage/NICEDamagePlugin.cs#L46

**Comment by gnargle** [comment]
Thanks for the headsup! This has been fixed with commit #412ee56c495519dd6fc2e4f2b6976a87b71a76d5 and should make its way through Dalamud soon.
