### ISSUE TITLE
this doesn't look right

### ISSUE THREAD

**Issue by K0shachiyamyatA** [gnargle/NICEDamage#3]
![ffxiv_dx11_nHoEg8ZvXm](https://github.com/user-attachments/assets/90358e71-b9c0-4c03-b0e1-a9b6c9d43bec)

**Comment by gnargle** [comment]
I may have forgotten to remove my testing code 🥲 fix incoming

**Comment by gnargle** [comment]
Resolved with commit #99576657283a88ccaea4544b93fe7b1b92fe3c11
